
package fr.atod26.webservice.fichier.lebaronjerome;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGestionImage", targetNamespace = "http://lebaronjerome.fichier.webservice.atod26.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGestionImage {


    /**
     * 
     * @param nomImage
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "imageRecuperee", targetNamespace = "")
    @RequestWrapper(localName = "recupererImage", targetNamespace = "http://lebaronjerome.fichier.webservice.atod26.fr", className = "fr.atod26.webservice.fichier.lebaronjerome.RecupererImage")
    @ResponseWrapper(localName = "recupererImageResponse", targetNamespace = "http://lebaronjerome.fichier.webservice.atod26.fr", className = "fr.atod26.webservice.fichier.lebaronjerome.RecupererImageResponse")
    public byte[] recupererImage(
        @WebParam(name = "nomImage", targetNamespace = "")
        String nomImage);

    /**
     * 
     * @param nomImage
     * @param image
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "imageEnvoyee", targetNamespace = "")
    @RequestWrapper(localName = "envoyerImage", targetNamespace = "http://lebaronjerome.fichier.webservice.atod26.fr", className = "fr.atod26.webservice.fichier.lebaronjerome.EnvoyerImage")
    @ResponseWrapper(localName = "envoyerImageResponse", targetNamespace = "http://lebaronjerome.fichier.webservice.atod26.fr", className = "fr.atod26.webservice.fichier.lebaronjerome.EnvoyerImageResponse")
    public String envoyerImage(
        @WebParam(name = "nomImage", targetNamespace = "")
        String nomImage,
        @WebParam(name = "image", targetNamespace = "")
        String image);

}
